### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by 25amalloy** [BinBashBanana/gfiles#8]
Game Crashed! I have fallen and I can't get up! If this has happened more than once then please copy the text on this screen and publish it in the issues feed of this fork's GitHub repository.

The URL to this fork's GitHub repository is: https://github.com/LAX1DUDE/eaglercraft

Native Browser Exception
----------------------------------
  Line: 17396:393
  Type: TypeError
  Message: Cannot read properties of null (reading 'data')
----------------------------------

TypeError: Cannot read properties of null (reading 'data')
    at Ck$ (https://dailylights.org/mc/classes.js:3408:29)
    at B38 (https://dailylights.org/mc/classes.js:3407:32)
    at Nx (https://dailylights.org/mc/classes.js:3363:47)
    at Csx (https://dailylights.org/mc/classes.js:9177:349)
    at Object.A.Tw (https://dailylights.org/mc/classes.js:9176:33)
    at BOM (https://dailylights.org/mc/classes.js:6110:24)
    at Object.A.VY (https://dailylights.org/mc/classes.js:6105:41)
    at A2C (https://dailylights.org/mc/classes.js:3092:285)
    at Bgx (https://dailylights.org/mc/classes.js:68:402)
    at BvE (https://dailylights.org/mc/classes.js:67:218)

eaglercraft.version = "22w15d"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "eagtek"
eaglercraft.username = "YeeYeeler41"
eaglercraft.channel = "YeeYeeler41_113"

window.minecraftOpts = ["game_frame","assets.epk","CgAACQAHc2VydmVycwoAAAABCAAKZm9yY2VkTU9URAAMRGVmYXVsdCBtb3RkAQALaGlkZUFkZHJlc3MBCAACaXAAGXdzczovL2RhaWx5bGlnaHRzLm9yZy9lYWcIAARuYW1lABNUaXRhbml1bU5ldHdvcmsgU01QAAA="]

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14588.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.59 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 4
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1188
rootElement.clientHeight = 668
window.innerWidth = 1188
window.innerHeight = 668
window.outerWidth = 1187
window.outerHeight = 667
window.devicePixelRatio = 1.149999976158142
window.screen.availWidth = 1187
window.screen.availHeight = 667
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.currentContext = [object WebGL2RenderingContext]

window.location.href = https://dailylights.org/mc/
window.location.ancestorOrigins = {}

----- Begin Minecraft Config -----
CgAAAwAIa2V5Lnpvb20AAAAuAwAMa2V5LnBpY2tJdGVt////ngEAD2NoYXRMaW5rc1Byb21wdAEDAAxrZXkuZnVuY3Rpb24AAAAhAwAIa2V5LmNoYXQAAAAUAwAKa2V5LnNwcmludAAAABMFAAtzb3VuZFZvbHVtZT+AAAABABBwYXRjaEFuaXNvdHJvcGljAAMADmNoYXRWaXNpYmlsaXR5AAAAAAMADWtleS5pbnZlbnRvcnkAAAASAQARaGlkZVNlcnZlckFkZHJlc3MACQAHc2VydmVycwEAAAAAAQALdmlld0JvYmJpbmcBAQAQYWR2YW5jZWRUb29sdGlwcwAFAAtjaGF0T3BhY2l0eT+AAAADAAhrZXkuYmFjawAAAB8DAApmb3JjZVdpZHRoAAAAAAMACGtleS5kcm9wAAAAEAEAEHBhdXNlT25Mb3N0Rm9jdXMBBQALc2Vuc2l0aXZpdHk/AAAABQALbXVzaWNWb2x1bWUAAAAABQAFZ2FtbWE/gAAAAwAJcGFydGljbGVzAAAAAAEAC2NoYXRDb2xvdXJzAQMAC2tleS5mb3J3YXJkAAAAEQMACGtleS5sZWZ0AAAAHgMACmtleS5hdHRhY2v///+cAwAMdmlld0Rpc3RhbmNlAAAAAQEAA2ZvZwEBAAljaGF0TGlua3MBAwAJa2V5LnNuZWFrAAAAKgUAA2ZvdgAAAAADAAlrZXkucmlnaHQAAAAgBQAJY2hhdFdpZHRoP4AAAAMACGd1aVNjYWxlAAAAAwMADmxpbWl0RnJhbWVyYXRlAAAAAQUACWNoYXRTY2FsZT+AAAABABRzZWVuQWNrbm93bGVkZ2VtZW50cwEDABBhbWJpZW50T2NjbHVzaW9uAAAAAAgACGxhbmd1YWdlAAVlbl9VUwEACGFuYWdseXBoAAEAEGhlbGRJdGVtVG9vbHRpcHMBBQARY2hhdEhlaWdodEZvY3VzZWQ/gAAAAQAKZnVsbFNjcmVlbgADAAhrZXkuanVtcAAAADkBAAZjbG91ZHMABQATY2hhdEhlaWdodFVuZm9jdXNlZD7jJ6kBAAt0b3VjaHNjcmVlbgADAA5rZXkucGxheWVybGlzdAAAAA8BAAtpbnZlcnRNb3VzZQABAAhzaG93Q2FwZQEDAA1hbnRpYWxpYXNNb2RlAAAAAQMAC2ZvcmNlSGVpZ2h0AAAAAAEADWZhbmN5R3JhcGhpY3MAAwAHa2V5LnVzZf///50IAApsYXN0U2VydmVyABl3c3M6Ly9kYWlseWxpZ2h0cy5vcmcvZWFnAA==
----- End Minecraft Config -----

window.minecraftServer = undefined

**Comment by BinBashBanana** [comment]
HOW DID YOU EVEN MESS UP THIS BAD?!
