### ISSUE TITLE
Flash emulator not working

### ISSUE THREAD

**Issue by manlycracker65** [BinBashBanana/gfiles#9]
every time I try to put in a flash game file from your list, this keeps popping up. 
![image](https://user-images.githubusercontent.com/103338779/190933328-4d9b8b38-36ec-4c6e-8fbc-68064946d4e6.png)

**Comment by BinBashBanana** [comment]
Read what it says lol. You can't use it from `file://`

**Comment by manlycracker65** [comment]
What does that even mean though, do I do the same thing as I did last time for the PlayStation emulator you made?

**Comment by BinBashBanana** [comment]
It means you can't use it from a `file://` URL.

**Comment by manlycracker65** [comment]
I still have no idea what you're taking about, explain it to me like i'm a 6 year old or something

**Comment by BinBashBanana** [comment]
![Screenshot 2022-09-24 215716](https://user-images.githubusercontent.com/51469593/192129037-5a963fb9-085d-4a4e-81c3-07723854bc0d.png)
If you see this, it won't work

**Comment by manlycracker65** [comment]
oh, that makes a lot more sense now, thanks
